pythonProject1/mysite/main/urls.py
from django.urls import path
from .views import index
from .views import other_page, RLogin, RLogout, profile, register, application, profile_bb_delete, profiledone, profileiw, superAdmin


app_name = 'main'

urlpatterns = [
   path('', index, name='index'),
   path('<str:page>/', other_page, name='other'),
   path('accounts/login/', RLogin.as_view(), name='login'),
   path('accounts/logout/', RLogout.as_view(), name='logout'),
   path('accounts/profile/addapplications/', application, name='application'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/profiledone/', profiledone, name='profiledone'),
   path('accounts/profileiw/', profileiw, name='profileiw'),
   path('accounts/register/', register, name='register'),
   path('accounts/profile/delete/<int:pk>', profile_bb_delete, name='profile_bb_delete'),
   path('accounts/profile/', profile, name='profile'),
   path('accounts/superadmin/', superAdmin, name='superAdmin'),
]

pythonProject1/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

from django.conf.urls.static import static


urlpatterns = [
   path('admin/', admin.site.urls),
   path('', include('main.urls', namespace='')),
]

if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pythonProject1/mysite/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .utilities import get_timestamp_path


class DefUser(AbstractUser):
    def is_author(self, bb):
        if self.pk == bb.author.pk:
            return True
        return False
    send_messages = models.BooleanField(default=True, verbose_name='Согласие на обработку персональных данных')

    fio = models.CharField(blank=True, max_length=150, verbose_name='ФИО', null=True)
    class Meta(AbstractUser.Meta):
        pass

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)


class Caregory(models.Model):
    name = models.CharField(max_length=64, verbose_name='название')

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        for bb in self.bb_set.all():
            bb.delete()
        super().delete(*args, **kwargs)

FORSTATUS = (
        ("Новая", "Новая"),
        ("Принято в работу", "Принято в работу"),
        ("Выполнено", "Выполнено"),
    )

class Bb(models.Model):
    title = models.CharField(blank=True, max_length=120, verbose_name='Название', null=True)
    description = models.TextField(blank=True, max_length=120, verbose_name='Описание', null=True)
    image = models.ImageField(blank=True, upload_to=get_timestamp_path, verbose_name='Изображение', null=True)
    author = models.ForeignKey(DefUser, on_delete=models.CASCADE, verbose_name='Автор', default=None, null=True)
    category = models.ForeignKey(Caregory, max_length=120, on_delete=models.CASCADE, verbose_name='категория')
    status = models.CharField(("status"), choices=FORSTATUS, blank=True, max_length=120, default="Новая", null=True)
    created = models.DateTimeField(auto_now_add=True)
    def delete(self, *args, **kwargs):
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Заявки'
        verbose_name = 'Заявку'

    def __str__(self):
        return self.title

class AddCommentary(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='Заявки')
    comment = models.CharField(max_length=64, verbose_name='Название')

    class Meta:
        verbose_name_plural = 'Комментарий'
        verbose_name = 'Комментарий'


class AdditionalImage(models.Model):
    bb = models.ForeignKey(Bb, on_delete=models.CASCADE, verbose_name='Заявки')
    image = models.ImageField(upload_to=get_timestamp_path, verbose_name='Изображение')

    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'

pythonProject1/mysite/main/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import DefUser, Bb, AdditionalImage, FORSTATUS
from django.forms import inlineformset_factory
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.contrib.messages import constants as messages


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Имя пользователя'}))
    fio = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'Фио'}),validators=[RegexValidator('([А-ЯЁ][а-яё]+[\-\s]?){3,}', message='ФИО введено не верно')])
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(attrs={'placeholder': 'Адрес электронной почты'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Повторите пароль'}))
    send_messages = forms.BooleanField(label='Согласие на обработку персональных данных', required=True)
    class Meta:
        model = DefUser
        fields = ('username', 'email', 'fio', 'password', 'password2', 'send_messages')
    #доделать
   # def fie_check(self):
       # fi = self.cleaned_data['fio']
       # check = [i for i in 'йцукенгшщзхъфывапролджэячсмитьбю ']
      #  for fi in check:
            #    if fi in check:
               #     raise forms.ValidationError('Только кириллица')
   #     return fi
    # доделать

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не соответствуют.')
        return cd['password2']


class CreateDesignForm(forms.ModelForm):
    title = forms.CharField(required=True, label="", widget=forms.TextInput(attrs={'placeholder': 'Название'}))
    description = forms.CharField(required=True, label="", widget=forms.Textarea(attrs={'placeholder': 'Описание'}))
    image = forms.ImageField(required=True, label="Изображение")
    class Meta:
        model = Bb
        fields = '__all__'
        widgets = {
                   'status': forms.HiddenInput,
                   'author': forms.HiddenInput,
                   'created': forms.HiddenInput,
                   }
AIFormSet = inlineformset_factory(Bb, AdditionalImage, fields='__all__')


class BbAdminForm(forms.ModelForm):
    def clean(self):
       status = self.cleaned_data['status']
       if (self.instance.status != status) and status == 'Новая':
           raise ValidationError("Вы не можете поменять статус на новая")
       if (self.instance.status == 'Выполнено'):
           raise ValidationError("Вы не можете поменять статус с Выполнено")
       if (self.instance.status == 'Принято в работу'):
           raise ValidationError("Вы не можете поменять статус с Принято в работу")

pythonProject1/mysite/main/views.py
import os.path
from django.contrib import messages
from django.contrib.messages import constants as messages
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_list_or_404, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin
from .forms import UserRegistrationForm, CreateDesignForm
from .models import Bb, AdditionalImage
from django.views.generic import DeleteView
import os


@login_required
def profile_bb_delete(request, pk):
   bb = get_object_or_404(Bb, pk=pk, status='Новая')
   if not request.user.is_author(bb):
       return redirect('main:profile')
   if request.method == 'POST':
       bb.delete()
       return redirect('main:profile')
   else:
       context = {'bb': bb}
       return render(request, 'main/profile_bb_delete.html', context)


def superAdmin(request):
    bbs = Bb.objects.all().order_by('-created')
    count = Bb.objects.filter(status='Принято в работу').count()
    context = {'bb': bbs, 'count': count}
    return render(request, 'main/superadmin.html', context)

# @login_required
# def profile_bb_change(request, pk):
#    bb = get_object_or_404(Bb, pk=pk)
#    if request.method == 'POST':
#        form = BbAdminForm(request.POST, request.FILES, instance=bb)
#        if form.is_valid():
#            bb = form.save()
#            formset = AIFormSet(request.POST, request.FILES, instance=bb)
#            if formset.is_valid():
#                formset.save()
#                messages.add_message(request, messages.SUCCESS,
#                                     'Объявление изменено')
#                return redirect('main:profile')
#    else:
#        form = BbAdminForm(instance=bb)
#        formset = AIFormSet(instance=bb)
#    context = {'form': form, 'formset': formset}

def index(request):
   bbs = Bb.objects.filter(status='Выполнено').order_by('-created')
   count = Bb.objects.filter(status='Принято в работу').count()
   context = {'bb': bbs, 'count': count}
   return render(request, 'main/index.html', context)


def other_page(request, page):
   try:
       template = get_template('main/' + page + '.html')
   except TemplateDoesNotExist:
       raise Http404
   return HttpResponse(template.render(request=request))


class RLogin(LoginView):
    template_name = 'main/login.html'


class RLogout(LogoutView, LoginRequiredMixin):
    template_name = 'main/logout.html'


@login_required
def profile(request):
   bbs = Bb.objects.filter(author=request.user.pk).order_by('-created')
   #ais = get_object_or_404(AdditionalImage)
  # ais = bbs.additionalimage_set.all()
   context = {'bbs': bbs}
   return render(request, 'main/profile.html', context)


@login_required
def profiledone(request):
   fil = Bb.objects.filter(author=request.user.pk, status='Выполнено').order_by('-created')
   context = {'fil': fil}
   return render(request, 'main/profilefilterobrabotka.html', context)


@login_required
def profileiw(request):
   iw = Bb.objects.filter(author=request.user.pk, status='Принято в работу').order_by('-created')
   context = {'iw': iw}
   return render(request, 'main/profileiw.html', context)


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'main/register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'main/register.html', {'user_form': user_form})


def application(request):
    if request.method == 'POST':
        form = CreateDesignForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('main:profile')

    else:
        form = CreateDesignForm(initial={'author': request.user.pk})
    return render(request, 'main/creating_an_application_for_the_development.html', {'application_form': form})


#@login_required
#def profile_bb_delete(request, pk):
  # bb = get_object_or_404(Bb, pk=pk)
#   if not request.user.is_author(bb):
  #     return redirect('main:profile')
 #  if request.method == 'POST':
  #     bb.delete()
   #    messages.add_message(request, messages.SUCCESS,
  #                          'Объявление удалено')
    #   return redirect('main:profile')
 #  else:
  #     context = {'bb': bb}
   #    return render(request, 'main/profile_bb_delete.html', context)

pythonProject1/mysite/main/templates/main/aboutus.html
{% extends "layout/base.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
   <h2>О сайте</h2>
   <p>Этот сайт предназначен для публикации электронных объявлений</p>
   <p>Все права оформлены и охраняются законом РФ</p>
{% endblock %}

pythonProject1/mysite/main/templates/main/creating_an_application_for_the_development.html
{% extends "layout/base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}
    <div class="lastFourApli">Создание заявки</div>
    <form class='createAppli' action="." method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="lastFourApli2">Заполните данную форму</div>
     <div class='forFormAppli'>{{ application_form.as_p }}
        <p><input class='deleteButton' type="submit" value="Отправить заявку"></p>
        </div>
    </form>
{% endblock %}

pythonProject1/mysite/main/templates/main/creating_an_application_for_the_development_done.html
{% extends "layout/base.html" %}

{% block title %}Добро пожаловать{% endblock %}

{% block content %}
    <h1>Заяка успешно создана. {{ new_user.first_name }}!</h1>
    <p> Посмотреть все заявки. <a href="#">log in</a>.</p>
{% endblock %}

pythonProject1/mysite/main/templates/main/index.html
{% extends "layout/base.html" %}

{% block content %}

<div class='forMainPicture'>
<img class='forMainPicture' src='media/main3.jpg'>
</div>

<div class='forTextInPicture'>
<div class='textPicture'></div>
</div>

<div class='textPictureeee'>DesignPro
</div>

   <div class="checkDown">
<div class="countCheck">
    <div class="countCheckEL">
    Количество заявок в статусе "Принято в работу"
    </div>
</div>
<div class="countCheckNumb">
    <div class="countCheckELTwo">
    {{ count }}
    </div>
   <div class="lastFourApli">Последние выполненные заявки</div>
   {% for post in bb %}
   <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div div class="forApplicationsAllETitle1">Создано: {{post.created}}</div>
   <div div class="forApplicationsAllETitle1">Автор поста: {{post.author}}</div>
   <div div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div div class="forApplicationsAllETitle1">Изображение:</div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>
   </div>

   {% endfor %}
{% endblock %}

pythonProject1/mysite/main/templates/main/logout.html
{% extends "layout/base.html" %}
{% block title %} Выход {% endblock %}

{% block content %}
   <p>Вы покинули сайт.</p>
{% endblock %}

pythonProject1/mysite/main/templates/main/profile.html
{% extends "layout/base.html" %}
{% block title %} Профиль  {% endblock %}

{% block content %}
<div class="profile">
   <h2>Пользоваетель: {{ user.username }}</h2>
   {% if user.fio %}
       <div>Здравствуйте, {{ user.fio }}
       </div>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% else %}
       <p>Здравствуйте! </p>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% endif %}
    <div class="lastFourApli">Все ваши объявления</div>
    <div><a href="{% url 'main:profile' %}">Все объвления</a></div>
    <div><a href="{% url 'main:profiledone' %}">Выполненные</a></div>
    <div><a href="{% url 'main:profileiw' %}">Приняты в работу</a></div>
    {% for post in bbs %}
    <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div class="forApplicationsAllETitle1">Статус вашей заявки: {{post.status}}</div>
   <div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div class="forApplicationsAllETitle1">Изображение: </div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>


   {% if post.status == 'Новая' %}  <div class="forApplicationsAllETitle"><a onclick="return confirm('Вы уверены что хотите удалить запись??')" href="{% url 'main:profile_bb_delete' post.id %}">Удалить</a></div>  {% endif %}



   </div>
   {% endfor %}
   </div>
{% endblock %}
<!-- <a href="{% url 'main:profile_bb_delete' post.id %}"></a> -->

pythonProject1/mysite/main/templates/main/profile_bb_change.html
{% extends "layout/base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}
    <h1>Создание заявки</h1>
    <p>Заполните данную форму</p>
    <form action="." method="post" enctype="multipart/form-data">
          {% csrf_token %}
     {{ application_form.as_p }}
        <p><input type="submit" value="Изменить"></p>
    </form>
{% endblock %}

pythonProject1/mysite/main/templates/main/profile_bb_delete.html
{% extends "layout/base.html" %}

{% block title %}Создание заявки{% endblock %}

{% block content %}
    <div class="lastFourApli">Удаление заявки</div>
    <form class='deleteAppli' method="post">
          {% csrf_token %}
        <p><input class='deleteButton' type="submit" value="Удалить"></p>
    </form>
{% endblock %}

pythonProject1/mysite/main/templates/main/profile_change.html
{% extends "layout/base.html" %}

{% block content %}
   <div class="lastFourApli">Последние выполненные заявки</div>
   {% for post in bb %}
   <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div div class="forApplicationsAllETitle1">Создано: {{post.created}}</div>
   <div div class="forApplicationsAllETitle1">Автор поста: {{post.author}}</div>
   <div div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div div class="forApplicationsAllETitle1">Изображение:</div>
   <div div class="forApplicationsAllETitle1">Статус: {{post.status}}</div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>
   </div>
   {% endfor %}
{% endblock %}

pythonProject1/mysite/main/templates/main/profilefilterobrabotka.html
{% extends "layout/base.html" %}
{% block title %} Профиль  {% endblock %}

{% block content %}
<div class="profile">
   <h2>Пользоваетель: {{ user.username }}</h2>
   {% if user.fio %}
       <div>Здравствуйте, {{ user.fio }}
       </div>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% else %}
       <p>Здравствуйте! </p>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% endif %}
    <div class="lastFourApli">Выполненные</div>
     <div><a href="{% url 'main:profile' %}">Все объвления</a></div>
    <div><a href="{% url 'main:profiledone' %}">Выполненные</a></div>
    <div><a href="{% url 'main:profileiw' %}">Приняты в работу</a></div>
    {% for post in fil %}
  <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div class="forApplicationsAllETitle1">Статус вашей заявки: {{post.status}}</div>
   <div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div class="forApplicationsAllETitle1">Изображение: </div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>


   {% if post.status == 'Новая' %}  <div class="forApplicationsAllETitle"><a onclick="return confirm('Вы уверены что хотите удалить запись??')" href="{% url 'main:profile_bb_delete' post.id %}">Удалить</a></div>  {% endif %}



   </div>
   {% endfor %}
   </div>
{% endblock %}

pythonProject1/mysite/main/templates/main/profileiw.html
{% extends "layout/base.html" %}
{% block title %} Профиль  {% endblock %}

{% block content %}
<div class="profile">
   <h2>Пользоваетель: {{ user.username }}</h2>
   {% if user.fio %}
       <div>Здравствуйте, {{ user.fio }}
       </div>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% else %}
       <p>Здравствуйте! </p>
 {% if user.email %}
        <div>Почта пользователя, {{user.email}} </div>
    {% else %}
        <div>Почта не введена</div>
    {% endif %}
   {% endif %}
   <div class="lastFourApli">Приняты в работу</div>
     <div><a href="{% url 'main:profile' %}">Все объвления</a></div>
    <div><a href="{% url 'main:profiledone' %}">Выполненные</a></div>
    <div><a href="{% url 'main:profileiw' %}">Приняты в работу</a></div>
    {% for post in iw %}
   <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div class="forApplicationsAllETitle1">Статус вашей заявки: {{post.status}}</div>
   <div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div class="forApplicationsAllETitle1">Изображение: </div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>


   {% if post.status == 'Новая' %}  <div class="forApplicationsAllETitle"><a onclick="return confirm('Вы уверены что хотите удалить запись??')" href="{% url 'main:profile_bb_delete' post.id %}">Удалить</a></div>  {% endif %}



   </div>
   {% endfor %}
   </div>
{% endblock %}

pythonProject1/mysite/main/templates/main/register.html
{% extends "layout/base.html" %}

{% block title %}Регистрация{% endblock %}

{% block content %}
    <div class="lastFourApli">Регистрация</div>
    <p class="lastFourApli2">Заполните данную форму</p>
    <form class='createAppli' action="." method="post">
        <div class='forFormAppli'>{{ user_form.as_p }}
        {% csrf_token %}
        <p><input class='deleteButton' type="submit" value="Создать аккаунт"></p>
        </div>
    </form>
{% endblock %}

pythonProject1/mysite/main/templates/main/register_done.html
{% extends "layout/base.html" %}

{% block title %}Добро пожаловать!{% endblock %}

{% block content %}
    <h1>Добро пожаловать! {{ new_user.first_name }}!</h1>
    <p>Ваш аккаунт успешно создан. Вы можете зайти в личный кабинет прямо сейчас! <a href="{% url 'main:login' %}">log in</a>.</p>
{% endblock %}

pythonProject1/mysite/main/templates/main/superadmin.html
{% extends "layout/base.html" %}

{% block content %}
   <div class="lastFourApli">Последние выполненные заявки</div>
   {% for post in bb %}
   <div class="forAllAppliInmain">
   <div class="forApplicationsAll">
   <div class="forApplicationsAllETitle">{{post.title}}</div>
   <div div class="forApplicationsAllETitle1">Создано: {{post.created}}</div>
   <div div class="forApplicationsAllETitle1">Автор поста: {{post.author}}</div>
   <div div class="forApplicationsAllETitle1">Описание: {{post.description}}</div>
   <div div class="forApplicationsAllETitle1">Категория: {{post.category}}</div>
   <div div class="forApplicationsAllETitle1">Изображение:</div>
   <div div class="forApplicationsAllETitle1">Статус: {{post.status}}</div>

   <div class="forApplicationsAllETitle1"><img class="forAllImg" src="{{MEDIA_URL}}{{ post.image.url }}" alt="Изображение"></div>
   </div>
   {% endfor %}
{% endblock %}